package dataTier.Entities;
// Generated 01-jul-2012 17:36:44 by Hibernate Tools 3.2.1.GA



/**
 * IntervalosepaTasasOcup generated by hbm2java
 */
public class IntervalosepaTasasOcup  implements java.io.Serializable {


     private Integer id;
     private int year;
     private int sexo;
     private int estudGr;
     private int edadGr;
     private int minT;
     private int p20T;
     private int p40T;
     private int p60T;
     private int p80T;
     private int maxT;

    public IntervalosepaTasasOcup() {
    }

    public IntervalosepaTasasOcup(int year, int sexo, int estudGr, int edadGr, int minT, int p20T, int p40T, int p60T, int p80T, int maxT) {
       this.year = year;
       this.sexo = sexo;
       this.estudGr = estudGr;
       this.edadGr = edadGr;
       this.minT = minT;
       this.p20T = p20T;
       this.p40T = p40T;
       this.p60T = p60T;
       this.p80T = p80T;
       this.maxT = maxT;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }
    public int getEstudGr() {
        return this.estudGr;
    }
    
    public void setEstudGr(int estudGr) {
        this.estudGr = estudGr;
    }
    public int getEdadGr() {
        return this.edadGr;
    }
    
    public void setEdadGr(int edadGr) {
        this.edadGr = edadGr;
    }
    public int getMinT() {
        return this.minT;
    }
    
    public void setMinT(int minT) {
        this.minT = minT;
    }
    public int getP20T() {
        return this.p20T;
    }
    
    public void setP20T(int p20T) {
        this.p20T = p20T;
    }
    public int getP40T() {
        return this.p40T;
    }
    
    public void setP40T(int p40T) {
        this.p40T = p40T;
    }
    public int getP60T() {
        return this.p60T;
    }
    
    public void setP60T(int p60T) {
        this.p60T = p60T;
    }
    public int getP80T() {
        return this.p80T;
    }
    
    public void setP80T(int p80T) {
        this.p80T = p80T;
    }
    public int getMaxT() {
        return this.maxT;
    }
    
    public void setMaxT(int maxT) {
        this.maxT = maxT;
    }




}


