package dataTier.Entities;
// Generated 01-jul-2012 17:36:44 by Hibernate Tools 3.2.1.GA



/**
 * IntervalosepaTasasOcupActiv generated by hbm2java
 */
public class IntervalosepaTasasOcupActiv  implements java.io.Serializable {


     private Integer id;
     private int year;
     private int sexo;
     private int estudGr;
     private int edadGr;
     private int minT;
     private int p20T;
     private int p40T;
     private int p60T;
     private int p80T;
     private int maxT;
     private int minT2;
     private int p20T2;
     private int p40T2;
     private int p60T2;
     private int p80T2;
     private int maxT2;

    public IntervalosepaTasasOcupActiv() {
    }

    public IntervalosepaTasasOcupActiv(int year, int sexo, int estudGr, int edadGr, int minT, int p20T, int p40T, int p60T, int p80T, int maxT, int minT2, int p20T2, int p40T2, int p60T2, int p80T2, int maxT2) {
       this.year = year;
       this.sexo = sexo;
       this.estudGr = estudGr;
       this.edadGr = edadGr;
       this.minT = minT;
       this.p20T = p20T;
       this.p40T = p40T;
       this.p60T = p60T;
       this.p80T = p80T;
       this.maxT = maxT;
       this.minT2 = minT2;
       this.p20T2 = p20T2;
       this.p40T2 = p40T2;
       this.p60T2 = p60T2;
       this.p80T2 = p80T2;
       this.maxT2 = maxT2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }
    public int getEstudGr() {
        return this.estudGr;
    }
    
    public void setEstudGr(int estudGr) {
        this.estudGr = estudGr;
    }
    public int getEdadGr() {
        return this.edadGr;
    }
    
    public void setEdadGr(int edadGr) {
        this.edadGr = edadGr;
    }
    public int getMinT() {
        return this.minT;
    }
    
    public void setMinT(int minT) {
        this.minT = minT;
    }
    public int getP20T() {
        return this.p20T;
    }
    
    public void setP20T(int p20T) {
        this.p20T = p20T;
    }
    public int getP40T() {
        return this.p40T;
    }
    
    public void setP40T(int p40T) {
        this.p40T = p40T;
    }
    public int getP60T() {
        return this.p60T;
    }
    
    public void setP60T(int p60T) {
        this.p60T = p60T;
    }
    public int getP80T() {
        return this.p80T;
    }
    
    public void setP80T(int p80T) {
        this.p80T = p80T;
    }
    public int getMaxT() {
        return this.maxT;
    }
    
    public void setMaxT(int maxT) {
        this.maxT = maxT;
    }
    public int getMinT2() {
        return this.minT2;
    }
    
    public void setMinT2(int minT2) {
        this.minT2 = minT2;
    }
    public int getP20T2() {
        return this.p20T2;
    }
    
    public void setP20T2(int p20T2) {
        this.p20T2 = p20T2;
    }
    public int getP40T2() {
        return this.p40T2;
    }
    
    public void setP40T2(int p40T2) {
        this.p40T2 = p40T2;
    }
    public int getP60T2() {
        return this.p60T2;
    }
    
    public void setP60T2(int p60T2) {
        this.p60T2 = p60T2;
    }
    public int getP80T2() {
        return this.p80T2;
    }
    
    public void setP80T2(int p80T2) {
        this.p80T2 = p80T2;
    }
    public int getMaxT2() {
        return this.maxT2;
    }
    
    public void setMaxT2(int maxT2) {
        this.maxT2 = maxT2;
    }




}


