package dataTier.Entities;
// Generated 01-jul-2012 17:36:44 by Hibernate Tools 3.2.1.GA



/**
 * Medidas generated by hbm2java
 */
public class Medidas  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;

    public Medidas() {
    }

    public Medidas(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


